routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Folders
    Route::delete('folders/destroy', 'FolderController@massDestroy')->name('folders.massDestroy');
    Route::resource('folders', 'FolderController');

    // Files
    Route::delete('files/destroy', 'FileController@massDestroy')->name('files.massDestroy');
    Route::post('files/media', 'FileController@storeMedia')->name('files.storeMedia');
    Route::post('files/ckmedia', 'FileController@storeCKEditorImages')->name('files.storeCKEditorImages');
    Route::resource('files', 'FileController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/File.php
<?php

namespace App\Models;

use Config;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use kornrunner\Blurhash\Blurhash;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use \DateTimeInterface;

class File extends Model implements HasMedia
{
    use InteractsWithMedia, HasFactory;

    public $table = 'files';

    protected $appends = [
        'data',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'folder_id',
        'blure_hash',
        'file_hash',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('origin')->format('webp');
        $this->addMediaConversion('origin')->format('jpg');
        $consersionArray = Config::get('media');
        foreach ($consersionArray as $convert){
            $this->addMediaConversion($convert['name'])->fit($convert['method'], $convert['width'], $convert['height'])->format($convert['format']);
        }
    }

    public function getBlureHash($file) : String {
        $fileForBlur  = $file;
        $image = imagecreatefromstring(file_get_contents($fileForBlur));
        $width = imagesx($image);
        $height = imagesy($image);

        $pixels = [];
        for ($y = 0; $y < $height; ++$y) {
            $row = [];
            for ($x = 0; $x < $width; ++$x) {
                $index = imagecolorat($image, $x, $y);
                $colors = imagecolorsforindex($image, $index);

                $row[] = [$colors['red'], $colors['green'], $colors['blue']];
            }
            $pixels[] = $row;
        }

        $components_x = 4;
        $components_y = 3;

        $blurhash = Blurhash::encode($pixels, $components_x, $components_y);

        return $blurhash;
    }

    public function getDataAttribute()
    {
        $file = $this->getMedia('data')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->preview   = $file->getUrl('preview');
        }

        return $file;
    }

    public function folder()
    {
        return $this->belongsTo(Folder::class, 'folder_id');
    }
}

app/Http/Controllers/Admin/FileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyFileRequest;
use App\Http\Requests\StoreFileRequest;
use App\Http\Requests\UpdateFileRequest;
use App\Models\File;
use App\Models\Folder;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class FileController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('file_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $files = File::with(['folder', 'media'])->get();

        $folders = Folder::get();

        return view('admin.files.index', compact('files', 'folders'));
    }

    public function create()
    {
        abort_if(Gate::denies('file_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $folders = Folder::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.files.create', compact('folders'));
    }

    public function store(StoreFileRequest $request)
    {
        $file = File::create($request->all());

        if ($request->input('data', false)) {
            $file->blure_hash = $file->getBlureHash(storage_path('tmp/uploads/' . basename($request->input('data'))));
            $file->addMedia(storage_path('tmp/uploads/' . basename($request->input('data'))))->toMediaCollection('data');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $file->id]);
        }
        $file->save();
        return redirect()->route('admin.files.index');
    }

    public function edit(File $file)
    {
        abort_if(Gate::denies('file_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $folders = Folder::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $file->load('folder');

        return view('admin.files.edit', compact('folders', 'file'));
    }

    public function update(UpdateFileRequest $request, File $file)
    {
        $file->update($request->all());

        if ($request->input('data', false)) {
            if (!$file->data || $request->input('data') !== $file->data->file_name) {
                if ($file->data) {
                    $file->data->delete();
                }
                $file->blure_hash = $file->getBlureHash(storage_path('tmp/uploads/' . basename($request->input('data'))));
                $file->addMedia(storage_path('tmp/uploads/' . basename($request->input('data'))))->toMediaCollection('data');
            }
        } elseif ($file->data) {
            $file->data->delete();
        }

        $file->save();
        return redirect()->route('admin.files.index');
    }

    public function show(File $file)
    {
        abort_if(Gate::denies('file_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $file->load('folder');

        return view('admin.files.show', compact('file'));
    }

    public function destroy(File $file)
    {
        abort_if(Gate::denies('file_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $file->delete();

        return back();
    }

    public function massDestroy(MassDestroyFileRequest $request)
    {
        File::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('file_create') && Gate::denies('file_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new File();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/files/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.file.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.files.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.file.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="data">{{ trans('cruds.file.fields.data') }}</label>
                <div class="needsclick dropzone {{ $errors->has('data') ? 'is-invalid' : '' }}" id="data-dropzone">
                </div>
                @if($errors->has('data'))
                    <span class="text-danger">{{ $errors->first('data') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.data_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="folder_id">{{ trans('cruds.file.fields.folder') }}</label>
                <select class="form-control select2 {{ $errors->has('folder') ? 'is-invalid' : '' }}" name="folder_id" id="folder_id" required>
                    @foreach($folders as $id => $folder)
                        <option value="{{ $id }}" {{ old('folder_id') == $id ? 'selected' : '' }}>{{ $folder }}</option>
                    @endforeach
                </select>
                @if($errors->has('folder'))
                    <span class="text-danger">{{ $errors->first('folder') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.folder_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="blure_hash">{{ trans('cruds.file.fields.blure_hash') }}</label>
                <input class="form-control {{ $errors->has('blure_hash') ? 'is-invalid' : '' }}" type="text" name="blure_hash" id="blure_hash" value="{{ old('blure_hash', '') }}">
                @if($errors->has('blure_hash'))
                    <span class="text-danger">{{ $errors->first('blure_hash') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.blure_hash_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="file_hash">{{ trans('cruds.file.fields.file_hash') }}</label>
                <input class="form-control {{ $errors->has('file_hash') ? 'is-invalid' : '' }}" type="text" name="file_hash" id="file_hash" value="{{ old('file_hash', '') }}">
                @if($errors->has('file_hash'))
                    <span class="text-danger">{{ $errors->first('file_hash') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.file_hash_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.dataDropzone = {
    url: '{{ route('admin.files.storeMedia') }}',
    maxFilesize: 512, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif,.webp',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 512,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="data"]').remove()
      $('form').append('<input type="hidden" name="data" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="data"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($file) && $file->data)
      var file = {!! json_encode($file->data) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="data" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/files/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.file.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.files.update", [$file->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.file.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $file->name) }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="data">{{ trans('cruds.file.fields.data') }}</label>
                <div class="needsclick dropzone {{ $errors->has('data') ? 'is-invalid' : '' }}" id="data-dropzone">
                </div>
                @if($errors->has('data'))
                    <span class="text-danger">{{ $errors->first('data') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.data_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="folder_id">{{ trans('cruds.file.fields.folder') }}</label>
                <select class="form-control select2 {{ $errors->has('folder') ? 'is-invalid' : '' }}" name="folder_id" id="folder_id" required>
                    @foreach($folders as $id => $folder)
                        <option value="{{ $id }}" {{ (old('folder_id') ? old('folder_id') : $file->folder->id ?? '') == $id ? 'selected' : '' }}>{{ $folder }}</option>
                    @endforeach
                </select>
                @if($errors->has('folder'))
                    <span class="text-danger">{{ $errors->first('folder') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.folder_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="blure_hash">{{ trans('cruds.file.fields.blure_hash') }}</label>
                <input class="form-control {{ $errors->has('blure_hash') ? 'is-invalid' : '' }}" type="text" name="blure_hash" id="blure_hash" value="{{ old('blure_hash', $file->blure_hash) }}">
                @if($errors->has('blure_hash'))
                    <span class="text-danger">{{ $errors->first('blure_hash') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.blure_hash_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="file_hash">{{ trans('cruds.file.fields.file_hash') }}</label>
                <input class="form-control {{ $errors->has('file_hash') ? 'is-invalid' : '' }}" type="text" name="file_hash" id="file_hash" value="{{ old('file_hash', $file->file_hash) }}">
                @if($errors->has('file_hash'))
                    <span class="text-danger">{{ $errors->first('file_hash') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.file.fields.file_hash_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.dataDropzone = {
    url: '{{ route('admin.files.storeMedia') }}',
    maxFilesize: 512, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif,.webp',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 512,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="data"]').remove()
      $('form').append('<input type="hidden" name="data" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="data"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($file) && $file->data)
      var file = {!! json_encode($file->data) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="data" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/files/index.blade.php
@extends('layouts.admin')
@section('content')
@can('file_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.files.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.file.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.file.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-File">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.file.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.file.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.file.fields.data') }}
                        </th>
                        <th>
                            {{ trans('cruds.file.fields.folder') }}
                        </th>
                        <th>
                            {{ trans('cruds.file.fields.blure_hash') }}
                        </th>
                        <th>
                            {{ trans('cruds.file.fields.file_hash') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                        </td>
                        <td>
                            <select class="search">
                                <option value>{{ trans('global.all') }}</option>
                                @foreach($folders as $key => $item)
                                    <option value="{{ $item->name }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($files as $key => $file)
                        <tr data-entry-id="{{ $file->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $file->id ?? '' }}
                            </td>
                            <td>
                                {{ $file->name ?? '' }}
                            </td>
                            <td>
                                @if($file->data)
                                    <a href="{{ $file->data->getUrl() }}" target="_blank" style="display: inline-block">
                                        <img src="{{ $file->data->getUrl('thumb') }}">
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $file->folder->name ?? '' }}
                            </td>
                            <td>
                                {{ $file->blure_hash ?? '' }}
                            </td>
                            <td>
                                {{ $file->file_hash ?? '' }}
                            </td>
                            <td>
                                @can('file_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.files.show', $file->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('file_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.files.edit', $file->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('file_delete')
                                    <form action="{{ route('admin.files.destroy', $file->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('file_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.files.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-File:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
let visibleColumnsIndexes = null;
$('.datatable thead').on('input', '.search', function () {
      let strict = $(this).attr('strict') || false
      let value = strict && this.value ? "^" + this.value + "$" : this.value

      let index = $(this).parent().index()
      if (visibleColumnsIndexes !== null) {
        index = visibleColumnsIndexes[index]
      }

      table
        .column(index)
        .search(value, strict)
        .draw()
  });
table.on('column-visibility.dt', function(e, settings, column, state) {
      visibleColumnsIndexes = []
      table.columns(":visible").every(function(colIdx) {
          visibleColumnsIndexes.push(colIdx);
      });
  })
})

</script>
@endsection

resources/views/admin/files/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.file.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.files.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.id') }}
                        </th>
                        <td>
                            {{ $file->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.name') }}
                        </th>
                        <td>
                            {{ $file->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.data') }}
                        </th>
                        <td>
                            @if($file->data)
                                <a href="{{ $file->data->getUrl() }}" target="_blank" style="display: inline-block">
                                    <img src="{{ $file->data->getUrl('thumb') }}">
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.folder') }}
                        </th>
                        <td>
                            {{ $file->folder->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.blure_hash') }}
                        </th>
                        <td>
                            {{ $file->blure_hash }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.file.fields.file_hash') }}
                        </th>
                        <td>
                            {{ $file->file_hash }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.files.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection